export const frontendItems = [
  { name: 'Algo Expert Logo', url: '/fe/algo-expert-logo' },
  { name: 'Algo Expert Products', url: '/fe/algo-expert-products' },
  { name: 'Array Methods', url: '/fe/array-methods' },
  { name: 'Blog Post', url: '/fe/blog-post' },
  { name: 'Connect Four', url: '/fe/connect-four' },
  { name: 'Corresponding Node', url: '/fe/corresponding-node' },
  { name: 'Create DOM', url: '/fe/create-d-o-m' },
  { name: 'Crypto Prices', url: '/fe/crypto-prices' },
  { name: 'Curry', url: '/fe/curry' },
  { name: 'Debounce', url: '/fe/debounce' },
  { name: 'Deep Equals', url: '/fe/deep-equals' },
  { name: 'Event Target', url: '/fe/event-target' },
  { name: 'Flatten', url: '/fe/flatten' },
  { name: 'Infinite Scroll', url: '/fe/infinite-scroll' },
  { name: 'Item Cart', url: '/fe/item-cart' },
  { name: 'Memoize', url: '/fe/memoize' },
  { name: 'Memory', url: '/fe/memory' },
  { name: 'Navbar', url: '/fe/navbar' },
  { name: 'Notifications Menu', url: '/fe/notifications-menu' },
  { name: 'Phone Input', url: '/fe/phone-input' },
  { name: 'Pig Emoji', url: '/fe/pig-emoji' },
  { name: 'Promise Methods', url: '/fe/promise-methods' },
  { name: 'Promises', url: '/fe/promises' },
  { name: 'Promisify', url: '/fe/promisify' },
  { name: 'Purchase Form', url: '/fe/purchase-form' },
  { name: 'Question List', url: '/fe/question-list' },
  { name: 'Quiz', url: '/fe/quiz' },
  { name: 'Rainbow Circles', url: '/fe/rainbow-circles' },
  { name: 'Robot Emoji', url: '/fe/robot-emoji' },
  { name: 'Sign Up Form', url: '/fe/sign-up-form' },
  { name: 'Spaghetti Recipe', url: '/fe/spaghetti-recipe' },
  { name: 'Stop Watch', url: '/fe/stop-watch' },
  { name: 'Sudoku', url: '/fe/sudoku' },
  { name: 'Testing Framework', url: '/fe/testing-framework' },
  { name: 'This Binding', url: '/fe/this-binding' },
  { name: 'Throttle', url: '/fe/throttle' },
  { name: 'Tic Tac Toe', url: '/fe/tic-tac-toe' },
  { name: 'Tier List', url: '/fe/tier-list' },
  { name: 'Tip Calculator', url: '/fe/tip-calculator' },
  { name: 'Toasts', url: '/fe/toasts' },
  { name: 'Todo List', url: '/fe/todo-list' },
  { name: 'Trending Stocks', url: '/fe/trending-stocks' },
  { name: 'Type Ahead', url: '/fe/type-ahead' },
  { name: 'Use /Fetch', url: '/fe/use-/fetch' },
  { name: 'Use Interval', url: '/fe/use-interval' },
  { name: 'Use Map', url: '/fe/use-map' },
  { name: 'Use State With History', url: '/fe/use-state-with-history' },
  { name: 'Use Window Size', url: '/fe/use-window-size' },
  { name: 'Wordle', url: '/fe/wordle' }
]
